# Generated by Django 3.0.5 on 2020-04-25 20:26

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='medicineslist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('duration', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(180), django.core.validators.MinValueValidator(1)])),
                ('times', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default=1, max_length=1)),
                ('medicine_times_m', models.BooleanField(blank=True, default=True)),
                ('medicine_times_a', models.BooleanField(blank=True, default=False)),
                ('medicine_times_n', models.BooleanField(blank=True, default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
